In [1]:
import pandas as pd

## Grouping data in pandas

In [ ]:
# Most common group by operations --> 
# mean(), sum(), count(), size(), max(), min(), median(), std(), agg()

In [7]:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "HR", "Sales", "IT"],
    "Salary": [50000, 40000, 60000, 45000, 55000, 70000],
    "Age": [25, 30, 28, 30, 27, 25]
})
df
df.groupby("Department") # It returns an object over which we can apply functions
df.groupby("Department")["Salary"].sum()
df.groupby("Department")["Salary"].mean()
df.groupby("Department",as_index = False).count()

  Department  Salary  Age
0         HR       2    2
1         IT       3    3
2      Sales       1    1

In [4]:
# Applying multiple aggregate functions simultaneoulsy
df.groupby("Department",as_index = False)["Salary"].agg(["mean", "max", "min"])

  Department     mean    max    min
0         HR  42500.0  45000  40000
1         IT  60000.0  70000  50000
2      Sales  55000.0  55000  55000

In [7]:
# Grouping by multiple columns
df.groupby(["Department","Age"],as_index = False)["Salary"].sum()

  Department  Age  Salary
0         HR   30   85000
1         IT   25  120000
2         IT   28   60000
3      Sales   27   55000

## Iterating over groups

In [9]:
grp = df.groupby("Department")
for name,group in grp:
    print(name)  # This print the name of the group
    print(group)  # This print the data inside the group 
    print()

HR
  Department  Salary  Age
1         HR   40000   30
3         HR   45000   30

IT
  Department  Salary  Age
0         IT   50000   25
2         IT   60000   28
5         IT   70000   25

Sales
  Department  Salary  Age
4      Sales   55000   27

## Selecting a particular group from groups

In [24]:
grp1 = df.groupby("Department")
grp1.get_group("IT") # It return the group of IT sector

  Department  Salary  Age
0         IT   50000   25
2         IT   60000   28
5         IT   70000   25

## Combining multiple column using dictionary aggregate function

In [4]:
data = pd.DataFrame({
    'Store': ['A', 'A', 'B', 'B', 'A', 'B'],
    'Product': ['Apple', 'Banana', 'Apple', 'Banana', 'Apple', 'Banana'],
    'Sales': [100, 150, 200, 100, 120, 180],
    'Quantity': [10, 20, 30, 40, 15, 35]
})
agg_dict = {"Sales":'sum',"Quantity":'mean'}  # Sum for Sales and mean for quantity
result = data.groupby("Store").agg(agg_dict).reset_index()
result
data

  Store Product  Sales  Quantity
0     A   Apple    100        10
1     A  Banana    150        20
2     B   Apple    200        30
3     B  Banana    100        40
4     A   Apple    120        15
5     B  Banana    180        35

In [5]:
# Multiple aggregation on single column
agg_dict1 = {"Sales":['max','min'],"Quantity":['max','min','median']}
r = data.groupby("Store").agg(agg_dict1).reset_index()
r

  Store Sales      Quantity
          max  min      max min median
0     A   150  100       20  10   15.0
1     B   200  100       40  30   35.0

In [6]:
# We can create our own custom aggregate function by using lambda functions
# Similarly we can create any kind of function according to our need 
agg_custom = {"Sales": lambda x: x.max()-x.min(), 'Quantity':'sum'}

re = data.groupby("Store").agg(agg_custom).reset_index()
re

  Store  Sales  Quantity
0     A     50        45
1     B    100       105

## Applying groupby function on IPL dataset

In [15]:
dft = pd.read_csv("matches.csv")
dft.head()

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [19]:
dft.groupby("team1")["win_by_runs"].sum()

team1
Chennai Super Kings            1594
Deccan Chargers                 421
Delhi Daredevils                596
Gujarat Lions                     1
Kings XI Punjab                 867
Kochi Tuskers Kerala             23
Kolkata Knight Riders           879
Mumbai Indians                 1532
Pune Warriors                   139
Rajasthan Royals                821
Rising Pune Supergiant          123
Rising Pune Supergiants           0
Royal Challengers Bangalore    1196
Sunrisers Hyderabad             510
Name: win_by_runs, dtype: int64

## Joining two dataset of same nature

In [19]:
# Creating custom dataset
data1 = pd.DataFrame({'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']},index=[0,1,2,3])

data2 = pd.DataFrame({'Name': ['Abhi', 'Ayushi', 'Dheeraj', 'Hitesh'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']},index=[4,5,6,7])
# Combining using pd.concat function
# After combining data1 and data2 
data1_data2_list = [data1,data2]
result = pd.concat(data1_data2_list)
result

      Name  Age    Address Qualification
0      Jai   27     Nagpur           Msc
1   Princi   24     Kanpur            MA
2   Gaurav   22  Allahabad           MCA
3     Anuj   32    Kannuaj           Phd
4     Abhi   17     Nagpur         Btech
5   Ayushi   14     Kanpur           B.A
6  Dheeraj   12  Allahabad          Bcom
7   Hitesh   52    Kannuaj        B.hons

## Working with text in pandas

In [20]:
data1 = pd.DataFrame({'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']},index=[0,1,2,3])
data1

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

In [28]:
data1["Name"] = data1["Name"].str.lower() # To lower the text
data1
data1["Address"] = data1["Address"].str.upper() # To capitalize the text
data1
data1.drop("Adress",axis = 1)

     Name  Age    Address Qualification
0     jai   27     NAGPUR           Msc
1  princi   24     KANPUR            MA
2  gaurav   22  ALLAHABAD           MCA
3    anuj   32    KANNUAJ           Phd

## Saving normal dataset to csv file

In [32]:
data1.to_csv("file1.csv",header = True,index = False)