## Selecting and slicing from the datafram or the table

In [2]:
import pandas as pd

In [7]:
#pd.read_csv('matches.csv').head()

In [2]:
df = pd.read_csv("matches.csv")
df.head()
df[['city','team1','team2','winner','toss_winner','toss_decision']].head(5)

,city,team1,team2,winner,toss_winner,toss_decision
0,Hyderabad,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,Royal Challengers Bangalore,field
1,Pune,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,Rising Pune Supergiant,field
2,Rajkot,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,Kolkata Knight Riders,field
3,Indore,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,Kings XI Punjab,field
4,Bangalore,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,bat

In [4]:
# Adding and deleting column in the existing dataframe.
# df['ball_color'] = 'White'
# df.head()
# df.drop('umpire3',axis=1,inplace = False) # umpire3 column has deleted permanently
# # Here axis = 1 means we are deleting the column and inplace = True means we are deleting this column permanently from the data set
# axis = 1 --> Column
# axis = 0 --> row
df.tail(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

#### Seleting row, adding row and deleting row

In [5]:
# Selection of the rows using loc function 
data = pd.read_csv("matches.csv",index_col = 'city') # Here we have to pass the index_col which is used to select the rows
first_row = data.loc[['Hyderabad']]  # Here we used the city column as index 
first_row.head()

,id,season,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
city,,,,,,,,,,,,,,,,,
Hyderabad,1,2017,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
Hyderabad,6,2017,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
Hyderabad,19,2017,2017-04-17,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN
Hyderabad,21,2017,2017-04-19,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,15,0,KS Williamson,"Rajiv Gandhi International Stadium, Uppal",CB Gaffaney,NJ Llong,NaN
Hyderabad,36,2017,2017-04-30,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,48,0,DA Warner,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,S Ravi,NaN

In [4]:
# Adding new row to the existing data  --> pd.concat()
new_row = {"id":637,"season":2019,"city":"Pune","date":"2019-04-30","team1":"CSK","team2":"MI","toss_winner":"csk","toss_decision":"bat","result":"Normal","dl_applied":0,"winner":"MI","win_by_runs":0,"win_by_wickets":8,"player_of_match":"Rohit Sharma","venue":"RJGS","umpire1":"A Nand"}
df = pd.concat([df,pd.DataFrame([new_row])],ignore_index = True)
df.tail(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN
636,637,2019,Pune,2019-04-30,CSK,MI,csk,bat,Normal,0,MI,0,8,Rohit Sharma,RJGS,A Nand,NaN,NaN

#### Getting column name from the dataset

In [8]:
# usefull when the data is large 
print(sorted(list(df.columns))) # we can sort the name of the column by using python sorted funtcion
df.columns.tolist()
# if we want the column name in numpy array then we can use df.columns.values
df.columns.values

# we can iterate over the column list
for col in df.columns:
    print(col,end=", ")

['city', 'date', 'dl_applied', 'id', 'player_of_match', 'result', 'season', 'team1', 'team2', 'toss_decision', 'toss_winner', 'umpire1', 'umpire2', 'umpire3', 'venue', 'win_by_runs', 'win_by_wickets', 'winner']
id, season, city, date, team1, team2, toss_winner, toss_decision, result, dl_applied, winner, win_by_runs, win_by_wickets, player_of_match, venue, umpire1, umpire2, umpire3,

## Renaming column name using pandas

In [13]:
# Using rename() funcion --> allows renaming specific columns by passing a dictionary, where keys are the old column names and values are the new column names.
df.rename(columns = {"season":"Year","city":"city_name"},inplace = True)
df.head(2)

,id,Year,city_name,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017.0,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017.0,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN

In [11]:
# By passing a list
data = {"A":[14,15],"B":[16,17],"C":[19,12]}
d_f = pd.DataFrame(data)
d_f
d_f.columns = ["X","Y","Z"] # We have to pass the same number of col_name as present in existing data frame
d_f       # Here "A","B","C" ---> "X","Y","Z"

    X   Y   Z
0  14  16  19
1  15  17  12

### Boolean indexing in pandas

In [8]:
# dictionary of lists
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

# creating a dataframe with boolean index 
dfd = pd.DataFrame(dict, index = [True, False, True, False]) # it creates the boolean index for each row
dfd
# accessing a dataframe using .loc[] function 
#print(dfd.loc[True])  # Selecting only those row having boolean index true

         name  degree  score
True   aparna     MBA     90
False  pankaj     BCA     40
True   sudhir  M.Tech     80
False   Geeku     MBA     98

In [16]:
# Example by myself
sport = {"Country":["England","India","America","Narve"],"Game":["Cricekt","Volleyball","Badminton","Football"],"Followers%":[95,70,75,80]}

dfs = pd.DataFrame(sport,index = [True,True,False,False])
dfs

dfs.loc[True]
dfs.loc[False]
#df.iloc[True] #--> It will give error because iloc() takes only integer based index not boolean based 
dfs.iloc[0:3]  # Row slicing

       Country        Game  Followers%
True   England     Cricekt          95
True     India  Volleyball          70
False  America   Badminton          75

In [27]:
# We can create a boolean mask (Basically a list of true and false to select the rows )
mask = [True,True,False,False]  # True means give first and second row only not third and fourth
dfs[mask]       # Pass the same length as number of columns

      Country        Game  Followers%
True  England     Cricekt          95
True    India  Volleyball          70

### Creating mask of different condtions and then fetch the rows using those condition

In [19]:
# Creating new dataframe
students = {"Name":["Rahul",'Ram','Abhishek','Hariom','Shyam'],'Age':[20,19,18,22,24],"Score":[95,98,96,94,97],'Stream':["PCM",'PCB','PCB','PCB','PCM']}
d_stu = pd.DataFrame(students)
d_stu

       Name  Age  Score Stream
0     Rahul   20     95    PCM
1       Ram   19     98    PCB
2  Abhishek   18     96    PCB
3    Hariom   22     94    PCB
4     Shyam   24     97    PCM

In [20]:
d_stu[(d_stu["Age"]>20) & (d_stu["Stream"]=="PCB")]

     Name  Age  Score Stream
3  Hariom   22     94    PCB

### DataFrame.truncate()

In [4]:
# To remove rows and columns from the dataset we use dataframe.truncate()
# Examples --> Creating dataframe 
Y = {"Name":["Ram","Raju","Ravi","Dharmraj","Shyam"],"Class":[10,11,10,12,10],"Stream":["Science","PCM","Science","PCM","Science"],"Roll_no":[101,102,103,104,105],"strem_id":["S-18","M-25","S-18","M-25","S-18"]}

# Creating index using date (New concept)
index_date = pd.date_range('2010-10-09 08:45', periods = 5, freq ='YE') # Here we can change the frequncey parameter to increase the index value 
dfy = pd.DataFrame(Y,index = index_date)                                # Here we can pass (hour = h, month = ME, Year = YE, etc)
dfy

                         Name  Class   Stream  Roll_no strem_id
2010-12-31 08:45:00       Ram     10  Science      101     S-18
2011-12-31 08:45:00      Raju     11      PCM      102     M-25
2012-12-31 08:45:00      Ravi     10  Science      103     S-18
2013-12-31 08:45:00  Dharmraj     12      PCM      104     M-25
2014-12-31 08:45:00     Shyam     10  Science      105     S-18

In [4]:
# Now using truncate() function to remove rows (truncate() remove rows by default)
row_truncate = dfy.truncate(before = "2011-12-31 08:45:00", after = "2013-12-31 08:45:00")
row_truncate # This result contain rows before "2011-12-31 08:45:00" and after "2013-12-31 08:45:00"

                         Name  Class   Stream  Roll_no strem_id
2011-12-31 08:45:00      Raju     11      PCM      102     M-25
2012-12-31 08:45:00      Ravi     10  Science      103     S-18
2013-12-31 08:45:00  Dharmraj     12      PCM      104     M-25

In [6]:
# Truncate by column (Remember to pass the before, after parameter in sorted order)
dfy_sorted = dfy.sort_index(axis = 1) # axis = 1 means sorted the column name 
dfy_sorted
col_truncate = dfy_sorted.truncate(after="Stream",before="Name",axis = 1)
col_truncate

                         Name  Roll_no   Stream
2010-12-31 08:45:00       Ram      101  Science
2011-12-31 08:45:00      Raju      102      PCM
2012-12-31 08:45:00      Ravi      103  Science
2013-12-31 08:45:00  Dharmraj      104      PCM
2014-12-31 08:45:00     Shyam      105  Science

In [6]:
# We can truncate the row and column using iloc function also
dfy.iloc[:,1:4]  # The first colon indicate that we are including aLL the rows , after comma we are selecting columns
dfy.iloc[1:3,1:4]

                     Class   Stream  Roll_no
2011-12-31 08:45:00     11      PCM      102
2012-12-31 08:45:00     10  Science      103

### Iterating over the rows and column of the dataframe

In [14]:
# Iterating over rows --> using iterrows()
for i,row in df.head(2).iterrows():
    print(i,row,end = ",")

0 id                                                         1
season                                                  2017
city                                               Hyderabad
date                                              2017-04-05
team1                                    Sunrisers Hyderabad
team2                            Royal Challengers Bangalore
toss_winner                      Royal Challengers Bangalore
toss_decision                                          field
result                                                normal
dl_applied                                                 0
winner                                   Sunrisers Hyderabad
win_by_runs                                               35
win_by_wickets                                             0
player_of_match                                 Yuvraj Singh
venue              Rajiv Gandhi International Stadium, Uppal
umpire1                                          AY Dandekar
umpire2                                             NJ Llong
umpire3                                                  NaN
Name: 0, dtype: object,1 id                                                       2
season                                                2017
city                                                  Pune
date                                            2017-04-06
team1                                       Mumbai Indians
team2                               Rising Pune Supergiant
toss_winner                         Rising Pune Supergiant
toss_decision                                        field
result                                              normal
dl_applied                                               0
winner                              Rising Pune Supergiant
win_by_runs                                              0
win_by_wickets                                           7
player_of_match                                  SPD Smith
venue              Maharashtra Cricket Association Stadium
umpire1                                     A Nand Kishore
umpire2                                             S Ravi
umpire3                                                NaN
Name: 1, dtype: object,

In [6]:
# Iterating over rows --> using itertuples()
for row in df.head(2).itertuples():
    print(row)
    print(" ")

Pandas(Index=0, id=1, season=2017, city='Hyderabad', date='2017-04-05', team1='Sunrisers Hyderabad', team2='Royal Challengers Bangalore', toss_winner='Royal Challengers Bangalore', toss_decision='field', result='normal', dl_applied=0, winner='Sunrisers Hyderabad', win_by_runs=35, win_by_wickets=0, player_of_match='Yuvraj Singh', venue='Rajiv Gandhi International Stadium, Uppal', umpire1='AY Dandekar', umpire2='NJ Llong', umpire3=nan)

Pandas(Index=1, id=2, season=2017, city='Pune', date='2017-04-06', team1='Mumbai Indians', team2='Rising Pune Supergiant', toss_winner='Rising Pune Supergiant', toss_decision='field', result='normal', dl_applied=0, winner='Rising Pune Supergiant', win_by_runs=0, win_by_wickets=7, player_of_match='SPD Smith', venue='Maharashtra Cricket Association Stadium', umpire1='A Nand Kishore', umpire2='S Ravi', umpire3=nan)

In [10]:
# Extracting using list comprehension 
name = [(row.team1,row.season) for row in df.head(5).itertuples()]
name

[('Sunrisers Hyderabad', 2017),
 ('Mumbai Indians', 2017),
 ('Gujarat Lions', 2017),
 ('Rising Pune Supergiant', 2017),
 ('Royal Challengers Bangalore', 2017)]

In [13]:
# Iterating over column --> using items()
for label,val in df.head(5).items():
    print(f"Columns: {label}")
    print(val)
    print()

Columns:id
0    1
1    2
2    3
3    4
4    5
Name: id, dtype: int64

Columns:season
0    2017
1    2017
2    2017
3    2017
4    2017
Name: season, dtype: int64

Columns:city
0    Hyderabad
1         Pune
2       Rajkot
3       Indore
4    Bangalore
Name: city, dtype: object

Columns:date
0    2017-04-05
1    2017-04-06
2    2017-04-07
3    2017-04-08
4    2017-04-08
Name: date, dtype: object

Columns:team1
0            Sunrisers Hyderabad
1                 Mumbai Indians
2                  Gujarat Lions
3         Rising Pune Supergiant
4    Royal Challengers Bangalore
Name: team1, dtype: object

Columns:team2
0    Royal Challengers Bangalore
1         Rising Pune Supergiant
2          Kolkata Knight Riders
3                Kings XI Punjab
4               Delhi Daredevils
Name: team2, dtype: object

Columns:toss_winner
0    Royal Challengers Bangalore
1         Rising Pune Supergiant
2          Kolkata Knight Riders
3                Kings XI Punjab
4    Royal Challengers Bangalore
Name: toss_winner, dtype: object

Columns:toss_decision
0    field
1    field
2    field
3    field
4      bat
Name: toss_decision, dtype: object

Columns:result
0    normal
1    normal
2    normal
3    normal
4    normal
Name: result, dtype: object

Columns:dl_applied
0    0
1    0
2    0
3    0
4    0
Name: dl_applied, dtype: int64

Columns:winner
0            Sunrisers Hyderabad
1         Rising Pune Supergiant
2          Kolkata Knight Riders
3                Kings XI Punjab
4    Royal Challengers Bangalore
Name: winner, dtype: object

Columns:win_by_runs
0    35
1     0
2     0
3     0
4    15
Name: win_by_runs, dtype: int64

Columns:win_by_wickets
0     0
1     7
2    10
3     6
4     0
Name: win_by_wickets, dtype: int64

Columns:player_of_match
0    Yuvraj Singh
1       SPD Smith
2         CA Lynn
3      GJ Maxwell
4       KM Jadhav
Name: player_of_match, dtype: object

Columns:venue
0    Rajiv Gandhi International Stadium, Uppal
1      Maharashtra Cricket Association Stadium
2       Saurashtra Cricket Association Stadium
3                       Holkar Cricket Stadium
4                        M Chinnaswamy Stadium
Name: venue, dtype: object

Columns:umpire1
0       AY Dandekar
1    A Nand Kishore
2       Nitin Menon
3      AK Chaudhary
4               NaN
Name: umpire1, dtype: object

Columns:umpire2
0         NJ Llong
1           S Ravi
2        CK Nandan
3    C Shamshuddin
4              NaN
Name: umpire2, dtype: object

Columns:umpire3
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: umpire3, dtype: float64

In [17]:
# To check the data type of each column and total non-null values --> We can modify easily before training the model
for label,val in df.items():
    print(f"{label}: Datatype: {val.dtype}, Total not_null values: {val.notnull().sum()}")

id: Datatype: int64, Total not_null values: 636
season: Datatype: int64, Total not_null values: 636
city: Datatype: object, Total not_null values: 629
date: Datatype: object, Total not_null values: 636
team1: Datatype: object, Total not_null values: 636
team2: Datatype: object, Total not_null values: 636
toss_winner: Datatype: object, Total not_null values: 636
toss_decision: Datatype: object, Total not_null values: 636
result: Datatype: object, Total not_null values: 636
dl_applied: Datatype: int64, Total not_null values: 636
winner: Datatype: object, Total not_null values: 633
win_by_runs: Datatype: int64, Total not_null values: 636
win_by_wickets: Datatype: int64, Total not_null values: 636
player_of_match: Datatype: object, Total not_null values: 633
venue: Datatype: object, Total not_null values: 636
umpire1: Datatype: object, Total not_null values: 635
umpire2: Datatype: object, Total not_null values: 635
umpire3: Datatype: float64, Total not_null values: 0

In [22]:
# Accessing specific value from the dataset
cols = list(df.columns)
for col in cols:
    print(f"Column_name: {col}:{df[col][2]}")

Column_name:id:3
Column_name:season:2017
Column_name:city:Rajkot
Column_name:date:2017-04-07
Column_name:team1:Gujarat Lions
Column_name:team2:Kolkata Knight Riders
Column_name:toss_winner:Kolkata Knight Riders
Column_name:toss_decision:field
Column_name:result:normal
Column_name:dl_applied:0
Column_name:winner:Kolkata Knight Riders
Column_name:win_by_runs:0
Column_name:win_by_wickets:10
Column_name:player_of_match:CA Lynn
Column_name:venue:Saurashtra Cricket Association Stadium
Column_name:umpire1:Nitin Menon
Column_name:umpire2:CK Nandan
Column_name:umpire3:nan

In [25]:
# Selecting numeric column only for statistically analysis.
num = df.select_dtypes(include = "number")
for col in num.columns:
    print(f"{col} mean: {num[col].mean()}")

id mean: 318.5
season mean: 2012.4905660377358
dl_applied mean: 0.025157232704402517
win_by_runs mean: 13.682389937106919
win_by_wickets mean: 3.3726415094339623
umpire3 mean: nan

### sorting dataframe using sort_values function

In [6]:
# Syntax: DataFrame.sort_values(by, axis=0, ascending=True, inplace=False, kind='quicksort', na_position='last')
df.sort_values(["season","date"], axis = 0,ascending = True,inplace = False, kind = 'quicksort',na_position='last').head()
# To sort by multiple values pass the list at the place of by parameter.
# We can sort with any sorting algorithm by passing the kind parameter

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
59,60,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
60,61,2008,Chandigarh,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN
61,62,2008,Delhi,2008-04-19,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,bat,normal,0,Delhi Daredevils,0,9,MF Maharoof,Feroz Shah Kotla,Aleem Dar,GA Pratapkumar,NaN
62,63,2008,Mumbai,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,normal,0,Royal Challengers Bangalore,0,5,MV Boucher,Wankhede Stadium,SJ Davis,DJ Harper,NaN
63,64,2008,Kolkata,2008-04-20,Deccan Chargers,Kolkata Knight Riders,Deccan Chargers,bat,normal,0,Kolkata Knight Riders,0,5,DJ Hussey,Eden Gardens,BF Bowden,K Hariharan,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,55,2017,Delhi,2017-05-14,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,10,0,HV Patel,Feroz Shah Kotla,CK Nandan,C Shamshuddin,NaN
55,56,2017,Mumbai,2017-05-16,Rising Pune Supergiant,Mumbai Indians,Mumbai Indians,field,normal,0,Rising Pune Supergiant,20,0,Washington Sundar,Wankhede Stadium,S Ravi,C Shamshuddin,NaN
56,57,2017,Bangalore,2017-05-17,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,1,Kolkata Knight Riders,0,7,NM Coulter-Nile,M Chinnaswamy Stadium,AK Chaudhary,Nitin Menon,NaN
57,58,2017,Bangalore,2017-05-19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,KV Sharma,M Chinnaswamy Stadium,NJ Llong,Nitin Menon,NaN
58,59,2017,Hyderabad,2017-05-21,Mumbai Indians,Rising Pune Supergiant,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,KH Pandya,"Rajiv Gandhi International Stadium, Uppal",NJ Llong,S Ravi,NaN

## Adding new rows to the existing data frame

In [26]:
data = {"Name" : ["Ram","Shyam"],"Age":[20,21]}
df = pd.DataFrame(data)
df
# Add row using loc function
df.loc[len(df)] = ["Charlie",25] # We have to specify the index where we add the row 
df
# Add row using concate function 
new_row = pd.DataFrame({"Name":["Bob"],"Age":[24]})
df = pd.concat([df,new_row],ignore_index = True)
df
# Adding multiple rows 
rows = pd.DataFrame({"Name":["Dheeraj","Prem","winston"],"Age":[20,26,28]})
df = pd.concat([df,rows],ignore_index = True)
df
# Adding row without one column
row = {"Name":"Alice"}
df = pd.concat([df,pd.DataFrame([row])],ignore_index = True)
df

      Name   Age
0      Ram  20.0
1    Shyam  21.0
2  Charlie  25.0
3      Bob  24.0
4  Dheeraj  20.0
5     Prem  26.0
6  winston  28.0
7    Alice   NaN

## Adding rows with condtions

In [18]:
data = {"Employee": ["Alice", "Bob"], "Salary": [5000, 6000]}
df = pd.DataFrame(data)
if(df["Salary"].max()<5000):
    df.loc[len(df)] = ["Charlie",8000]
df

  Employee  Salary
0    Alice    5000
1      Bob    6000